### ISSUE TITLE
gc editing to make it like in insta

### ISSUE THREAD

**Issue by justmohamedd** [Vencord/plugin-requests#133]
### Plugin Description

plugin to make gcs still visible after getting removed with all the msgs sent before remove visible

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Sqaaakoi** [comment]
this almost certainly wont be added

1. This would require caching LOADS of data on clients, and would only store messages recieved/fetched while Vencord is open
2. Vencord devs do not like to store that data on the client for the sake of other people's privacy, that's why MessageLogger doesn't save messages to any form of long-term storage by design
3. This would require a lot of (buggy) logic to fake channels client-side
