### ISSUE TITLE
RicherCider

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [Vencord/plugin-requests#146]
### Plugin Description

A fix for Cider not being correctly presented in the RPC ("Playing a game" instead of  "Listening to ..."). They've already made a 3rd party plugin to fix it but it'd be nice if it was officially added.

### Existing Plugin for other mod

https://github.com/ciderapp/RicherCider-Vencord

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
RicherCider plugin was actually merged a bit over a year ago. Not sure why or when it got removed.

https://github.com/Vendicated/Vencord/pull/471
https://github.com/Vendicated/Vencord/commit/8a5218937838a9bc7e40304b885af2a30adfbff1

**Comment by nyakowint** [comment]
Why it was removed: https://discord.com/channels/1015060230222131221/1032770730703716362/1088937127087194275
> I removed it because it doesn't comply with our code of conduct, this is not something I want our project to be associated with
 https://www.reddit.com/r/AppleMusic/comments/vydyj8/i_know_everyone_likes_cider_but_the_devs_are/
the commit removing it just gave me a good opportunity to remove it because it didn't comply with the structure required by that feature anyway. I didn't mention it further because I was hoping it would just fly under the radar, since I don't really want to start silly drama over this
