### ISSUE TITLE
Third-party JavaScript Uploaders/JS Plugin Uploader

### ISSUE THREAD

**Issue by glitchedtahcat** [Vencord/plugin-requests#237]
### Plugin Description

Like How it is for upload themes and stuff like that but where you could make you are own JavaScript plugins or download others to make the vencord experience nicer and this would make more people happier cuz they could either make there own plugins or download them instead of waiting for one the devs to make it

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nin0-dev** [comment]
Entire point of vencord is that plugins come bundled with the mod, which avoids BD-like scenarios where plugin devs take months to fix the plugins when major updates happen, or allow bad/laggy code to be ran in Vencord

I honestly don't see this going anywhere, especially since someone PRed a custom plugin loader once and the pr got closed for not following the "spirit" of Vencord

**Comment by nin0-dev** [comment]
oh and also read #216, sums up my point pretty well
