### ISSUE TITLE
Something similar to pluralchum

### ISSUE THREAD

**Issue by gllxflr** [Vencord/plugin-requests#331]
### Plugin Description

Adds integration with PluralKit to replace the BOT tag, as well as providing nickname colouring using the PluralKit API. More could be added such as filling out the popout profile with the proper PluralKit banner and description.

### Existing Plugin for other mod

https://github.com/estroBiologist/pluralchum

### Request Agreement

- [x] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by lynxize** [comment]
I know it's way too niche to ever be accepted as an included plugin (see https://github.com/Vendicated/Vencord/pull/2536/#issuecomment-2143917513) but I did make a thing that's basically just PluralChum for Vencord. (More information in [the plugin file itself](
https://github.com/lynxize/vencord-plugins/blob/plugins/src/userplugins/pk4vc/index.tsx))
I'm also [not the first person to try to do this](https://github.com/ScyyeCord/Vencord/blob/main/src/userplugins/pluralKit/index.tsx).

I don't really suggest/encourage using it because I don't really have any idea what I'm doing, and it conflicts with a couple of plugins (`ShowMeYourName`, `MessageLogger`, and `MoreUserTags`). Consider it mostly a proof of concept, I guess.
