### ISSUE TITLE
More Alts

### ISSUE THREAD

**Issue by VillainsRule** [Vencord/plugin-requests#35]
### Plugin Description

I don't know if this is fully possible, but Discord allows a maximum of five alternative accounts in the selector. It'd be nice if we could have more.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by fily-gif** [comment]
imo 6 accounts is a reasonable limit, why would you ever need more than 6 accounts??

**Comment by Riddim-GLiTCH** [comment]
I would just like to say that the average discord user only ever realistically needs 2 accounts.
One for being on discord, and another one for testing. While I can somewhat understand having a third because of non-nitro server limits, needing 4 or more is honestly kinda suspicious and no one in their right mind would honestly use more than 3 accounts.
