### ISSUE TITLE
Completely remove all decorations from people's profiles

### ISSUE THREAD

**Issue by sergiohzph** [Vencord/plugin-requests#403]
### Plugin Description

It would not really be necessary to create a new plugin, adding this option to the existing NoProfileThemes plugin would be enough. I hate Nitro and paid profile decorations in general, luckily I was already able to remove the avatar clown decorations, but I don't know how to remove the profile effects.

### Existing Plugin for other mod

https://vencord.dev/plugins/NoProfileThemes

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
css

**Comment by Feathers8** [comment]
As the average user, I had to use Discord's search to find it in Vencord's server. A nice little toggle in NoProfileThemes's settings would've been convenient.

**Comment by Vendicated** [comment]
our policy is that anything that can reasonably be done with css will not become a plugin, because css is simply better suited for such minor tweaks. as such no this will not be added to the plugin.. if we started doing that, people would quickly ask us to include more and more tweaks (e.g. hiding gift button, nitro stuff, etc)

we just need better discoverability for useful css snippets. e.g. a snippet store that is always kept updated

**Comment by nin0-dev** [comment]
> Petition to add a "Plugins"-like menu for CSS on Vencord

has been requested: #344, so if you have any feedback direct it here
