### ISSUE TITLE
VolumeBooster

### ISSUE THREAD

**Issue by LOSEARDES77** [Vencord/plugin-requests#500]
### Plugin Description

I know it exist in [here](https://vencord.dev/plugins/VolumeBooster) 
But i cant find it on the in-app search for Vesktop

![image](https://github.com/Vencord/plugin-requests/assets/84414230/b63fdbc8-a1bb-4715-8326-6549bdde162e)

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by LOSEARDES77** [comment]
is it just unimplemented for Vesktop yet or something? or is it an issue i have?
I have tryed enabling it throw the config but didn't work

**Comment by nvhhr** [comment]
Vesktop works very differently because it's essentially just a browser and doesn't have the powers of the desktop application, big technical hurdle to overcome but maybe some day.
https://github.com/Vencord/Vesktop/issues/331
See also: [Vesktop roadmap](https://github.com/Vencord/Vesktop/issues/324)
