### ISSUE TITLE
VIM inspired keyboard shortcuts

### ISSUE THREAD

**Issue by Fireb3rt** [Vencord/plugin-requests#533]
### Plugin Description

[Surfingkeys](https://github.com/brookhong/Surfingkeys)/[Vimium](https://vimium.github.io/) type plugin with VIM inspired keyboard shortcuts for navigating discord without cursor input

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Spiderfffun** [comment]
I think we probably want something more like [firenvim](https://github.com/glacambre/firenvi://github.com/glacambre/firenvim) as well. But possibly having a keyboard shortcut (or insert mode by default), so it doesn't get that annoying.

I also think a command bar could be just enough in some cases (for opening all the special buttons), since control-k is already pretty good.
