### ISSUE TITLE
Automatically disable Custom Voice Activity

### ISSUE THREAD

**Issue by Duckrinium** [Vencord/plugin-requests#564]
### Plugin Description

Context: Joining voice channel automatically sets custom voice activity to "Chilling" or custom one, with no ability to set it to none by default.
![image](https://github.com/Vencord/plugin-requests/assets/37019004/dc32fd2c-ad01-4f8f-8476-72ca163dc1b3)
It also tells others that you're currently in a voice channel, even if they can't see voice channel or don't even share the server (in some cases).

Basically what this plug-in would do it will set the custom voice activity to "Clear Status" when you join voice channel. Or somehow prevent from setting it altogether.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Nqfth** [comment]
please add this

**Comment by D3SOX** [comment]
Can you test if [this](https://github.com/D3SOX/vencord-userplugins/tree/master/noDefaultHangStatus) works as intended?

**Comment by D3SOX** [comment]
Released

**Comment by ravenhehe** [comment]
@D3SOX 

Hi! I was looking for this plugin a few days ago but couldn't find it while searching. 

I recommend adding a few keywords like "activity" "voice status" etc so that people can find it by searching. I haven't heard of it being called a hang status until now.

Regardless, thank you for the plugin. I hate that Discord doesn't give the option to disable this.
