### ISSUE TITLE
Spellchecker

### ISSUE THREAD

**Issue by DrWhoFan13** [Vencord/plugin-requests#7]
### Plugin Description

A plugin that provides built-in spellcheck by right-clicking on a word that was typed incorrectly.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/SpellCheck

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by Vendicated** [comment]
??

**Comment by DaavyC** [comment]
Would it be possible to have a plugin that forces the language that discord should use when correcting?

Because I have been suffering from a problem where discord often suggests the wrong word that is from another language.

**Example:**
![image](https://github.com/Vencord/plugin-requests/assets/109737628/d169b5d1-8049-481d-bcd0-206566fb2608)

The word above **“Ocorrerá”** means **“will happen”** and is correct, however discord says no and recommends another word that has nothing to do with it.
