### ISSUE TITLE
Userplugins tab

### ISSUE THREAD

**Issue by TheToxicDog** [Vencord/plugin-requests#795]
### Plugin Description

A plugin that adds a userplugins tab to access only custom plugins inside of the userplugins folder, if there is one.

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [ ] I checked every box, despite not reading any
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by jamesbt365** [comment]
Not a vencord dev but I'm almost certainly sure its done this way by *choice*.

Letting users add in files that are not controlled by vencord itself can and does lead to crashes when either Discord or Vencord changes something major.

This is most likely why you must compile vencord with userplugins that you want. Considering the devs do not provide support for users running these builds in most cases this is kept this way because they do not have the intention of dealing with the technical debt.

Even if Vencord supported this you would still need to have the correct tooling on your system to build those plugins into Vencord! (unless i'm missing some magic injection jank)

**Comment by Scyye** [comment]
> Not a vencord dev
considering your message makes little to no sense, i can see that.

**Comment by Scyye** [comment]
> Letting users add in files that are not controlled by vencord itself can and does lead to crashes when either Discord or Vencord changes something major.

Users are able to import their own plugins, by creating plugin folders/files in `src/userplugins`. This is simply another directory to load plugins from, along with `src/plugins`.

> Even if Vencord supported this you would still need to have the correct tooling on your system to build those plugins into Vencord! (unless i'm missing some magic injection jank)

yea, and if you were developing plugins (or had a `src/userplugins` directory, at the very least), you would have said "tooling".

(afaik) this user is asking for a seperate tab in the vencord settings, to view what was added via `src/userplugins` rather than displaying them in the list in the plugins tab, along with plugins added via `src/plugins`

**Comment by Vendicated** [comment]
no. adding third party plugins will never be officially supported. use BetterDiscord if you want that

**Comment by Scyye** [comment]
> no. adding third party plugins will never be officially supported. use BetterDiscord if you want that

This is on the same level of `officially supporting TPPs` as like, the patch helper, or the fact that you can load plugins from `userplugins`, its just a utility for developers.
